2020/09/03 05:40:23 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: example.localhost, request: "GET /api/swagger/v1/ HTTP/1.1", upstream: "http://172.18.0.3:3010/api/swagger/v1/", host: "example.localhost:8080"
2020/09/03 05:40:29 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.18.0.3:3010/api/users", host: "example.localhost:8080"
2020/09/03 05:41:59 [error] 28#28: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.18.0.3:3010/api/users", host: "example.localhost:8080"
2020/09/03 05:42:27 [error] 28#28: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.18.0.3:3010/api/users", host: "example.localhost:8080"
2020/09/03 10:12:37 [error] 27#27: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.20.0.3:3010/api/users", host: "example.localhost:8080"
2020/09/03 10:12:38 [error] 27#27: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.20.0.3:3010/api/users", host: "example.localhost:8080"
2020/09/03 10:12:39 [error] 27#27: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: example.localhost, request: "GET /api/users HTTP/1.1", upstream: "http://172.20.0.3:3010/api/users", host: "example.localhost:8080"
